--- #YAML:1.0
name:               Device-Velleman-K8055-libk8055
version:            0.04
abstract:           Communication with the Velleman K8055 USB experiment board via libk8055 
author:
    - Vlatko Kosturjak <kost@linux.hr>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Device-Velleman-K8055-libk8055
    repository:  http://github.com/kost/libk8055-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
